In [6]:
from IPython.core.display import HTML
def css_styling():
    styles = open("./styles/custom.css", "r").read()
    return HTML(styles)
css_styling()

### BEFORE YOU DO ANYTHING...
In the terminal:
1. Navigate to __inside__ your ILAS_Python repository.
2. __COMMIT__ any un-commited work on your personal computer.
3. __PULL__ any changes *you* have made using another computer.
4. __PULL__ textbook updates (including homework answers).

1. __Open Jupyter notebook:__   Start >> Programs (すべてのプログラム) >> Programming >> Anaconda3 >> JupyterNotebook
1. __Navigate to the ILAS_Python folder__. 
1. __Open today's seminar__  by clicking on 7_Numerical_computation_with_Numpy.

<h1>Numerical Computation with Numpy</h1> 

<h1>Lesson Goal</h1> 

Compose programs to solve simple mathematical problems using the Python Numpy package. 

## Objectives
- Represent data using the `array` data structure for numerical computation.
- Use 1D and 2D arrays to represent vectors and matrices. 
- Manipulate arrays (indexing, slicing, vectorising etc)
- Perform familiar numerical operations using Python.
- Compare efficiency of vectorised and non-vectorised functions.

## Why are we studying this?
Numerical computation is central to almost all scientific and engineering problems.

There are programming languages specifically designed for numerical computation:
- Fortran
- MATLAB

There are libaries dedicated to efficient numerical computations:
- Numpy
- Scipy
- Sympy ...

NumPy (http://www.numpy.org/) 
 - The most widely used Python library for numerical computations. 
 - Large, extensive library of data structures and functions for numerical computation.
 - Useful for perfoming operation you will learn on mathematics-based courses.


Scipy (https://www.scipy.org/)
- Builds on Numpy, additional functionality
- More specialised data structures and functions over NumPy.




If you are familiar with MATLAB, NumPy and SciPy provide similar functionality. 



Last week we covered an introduction to some basic functions of Numpy.

NumPy is a very extensisve library.

This seminar will:
- Introduce some useful functions
- Briefly discuss how to search for additional functions you may need. 

your best resources are search engines, such as http://stackoverflow.com/.



## Importing the NumPy module

To make NumPy functions and variables available to use in our program in our programs, we need to __import__ it using.

`import numpy`

We typically import all modules at the start of a program or notebook. 

In [3]:
import numpy as np

The shortened name `np` is often used for numpy. 

All Numpy functions can be called using `np.function()`. 

## Data Structure: The Numpy `array`

### Why do we need another data structure?

Python lists hold 'arrays' of data. 

Lists are very flexible. e.g. holding mixed data type.

There is a trade off between flexibility and performance e.g. speed.

Science engineering and mathematics problems often involve large amounts of data and numerous operations. 

We therefore use specialised functions and data structures for numerical computation.

## Numpy array

A numpy array is a grid of values, *all of the same type*.

To create an array we use the Numpy `np.array()` function.

We can create an array in a number of ways.

Let's start with something that is already familiar to you...

We can give a data structure (list, tuple) as an *argument* to convert it to a numpy array:

In [15]:
a = (4.0,)

b = np.array(a) 

print(type(a))
print(type(b))
print(b.dtype)

<class 'tuple'>
<class 'numpy.ndarray'>
float64


The method `dtype` tells us the type of the data contained in the array.

__Note:__The data type can be optionally set by the user when creating the array. This can be useful The data types are there when you need more control over how your data is stored in memory and on disk. Especially in cases where you’re working with large data, it’s good that you know to control the storage type. 


In [16]:
c = [4.0, 5, 6.0]

d = np.array(c) 

print(type(c))
print(type(d))
print(d.dtype)

<class 'list'>
<class 'numpy.ndarray'>
float64


## Multi-dimensional arrays.

Unlike the data types we have studied so far, arrays can have multiple dimensions.

__`rank`:__ the number of *dimensons* of the array.

__`shape`:__ a *tuple* of *integers* giving the *size* of the array along each *dimension*.

In [10]:
# 1-dimensional array
a = np.array([1, 2, 3])

# 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

c = np.array(
    [[[1, 1],
      [1, 1]],
     
     [[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

(2, 2, 2)
(3, 2, 2)


In [12]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

# 4-dimensional array
d = np.array(
    [[[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]],


      [[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]]])

print(c.shape)
print(d.shape)

(2, 2, 2)
(2, 2, 2, 2)


## Creating a numpy array.

There are several other ways we can create an array

For example, if you don’t know what data you want to put in your array you can initialise it with placeholders and load the data you want to use later. 


In [17]:
# Create an empty matrix
# The empty() function argument is the shape.
# Shape: tuple of integers giving the size along each dimension.

x = np.empty((4))
print(x)

print()

x = np.empty((4,4))
print(x)

[  6.92917829e-310   4.65980589e-310   6.92917450e-310   6.92916609e-310]

[[  6.92917829e-310   4.65980626e-310   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   1.39069238e-309]]


In [20]:
# Create an array of elements with the same value 
# The full() function arguments are
# 1) Shape: tuple of integers giving the size along each dimension.
# 2) The constant value

y = np.full((1,1), 3)
print(y)
print(y.shape)

print()

y = np.full((2,2), 4)   
print(y)  

[[3]]
(1, 1)

[[4 4]
 [4 4]]


In [21]:
# Create a 1D array of evenly spaced values
# The arange() function arguments are the same as the range() function. 
# Shape: tuple of integers giving the size along each dimension.

z = np.arange(5,10)
print(z)

print()

z = np.arange(5, 10, 2)   
print(z)  

[5 6 7 8 9]

[5 7 9]


In [13]:
# Create an array of all zeros
# The zeros() function argument is the shape.
# Shape: tuple of integers giving the size along each dimension.

a = np.zeros(5)
print(a)

print()

a = np.zeros((2,2))   
print(a)  

[ 0.  0.  0.  0.  0.]

[[ 0.  0.]
 [ 0.  0.]]


In [22]:
# Create an array of all ones

b = np.ones(5)
print(b)

print()

b = np.ones((1, 4))    
print(b)  

[ 1.  1.  1.  1.  1.]

[[ 1.  1.  1.  1.]]


In [23]:
# Create a constant array
# The second function argument is the constant value

c = np.full(6, 8)
print(c)

print()

c = np.full((2,2,2), 7)  
print(c)               


[8 8 8 8 8 8]

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


## Subpackages
Packages can also have subpackages. 

The `numpy` package has a subpackage called `random`.

It contains functions to deal with random variables. 

If the `numpy` package is imported with `import numpy as np`, functions in the `random` subpackage can be called using `np.random.function()`. 

In [33]:
# Create an array filled with random values

e = np.random.rand(1)
print(e)
print()

e = np.random.rand(3,2,1)
print(e)
print()

e = np.random.random((2,2))  
print(e)

[ 0.1925726]

[[[ 0.79990402]
  [ 0.63879192]]

 [[ 0.38519791]
  [ 0.0073061 ]]

 [[ 0.9293842 ]
  [ 0.77903214]]]

[[ 0.09380194  0.32369848]
 [ 0.72059049  0.03877658]]


In [ ]:
# Create an array filled with random integrer values

In [ ]:
e = np.random.randint(16, size=(4,4))
print(e)

print()

e = np.random.randint(8, size=(2, 2, 2))
print(e)

## Indexing.

We can index into an array exactly the same way as the other data structures we have studied.

In [17]:
x = np.array([1, 2, 3, 4, 5])

# Select a single element
print(x[4])

# Select elements from 2 to the end
print(x[2:])

5
[3, 4, 5]


For an n-dimensional (nD) matrix we need n index values to address an element or range of elements.

Example: The index of a 2D array is specified with two values:
- first the row index
- then the column index.

Note the order in which dimensions are addressed.

In [18]:
# 2 dimensional array

y = np.array([[1, 2, 3], 
              [4, 5, 6]])


# Select a single element
print(y[1,2])

# Select elements that are both in rows 1 to the end AND columns 0 to 2 
print(y[1:, 0:2])

6
[[4 5]]


We can address elements by selecting a range with a step by addig a 

For example the index:

`z[0, 0:]`

selects every element of row 0 in array, `z`

The index:

`z[0, 0::2]`

selects every *other* element of row 0 in array, `z`

In [18]:
# 2 dimensional array

z = np.zeros((4,8))

# Change every element of row 0
z[0, 0:] = 10

# Change every other element of row 1
z[1, 0::2] = 10

print(z)

[[ 10.  10.  10.  10.  10.  10.  10.  10.]
 [ 10.   0.  10.   0.  10.   0.  10.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


In [19]:
z = np.zeros((4,8))

# Change the last 4 elements of row 2, in negative direction
# You MUST include a step to count in the negative direction
z[2, -1:-5:-1] = 10

# Change every other element of the last 6 elements of row 3
# in negative direction
z[3, -2:-7:-2] = 10

print(z)

[[  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  10.  10.  10.  10.]
 [  0.   0.  10.   0.  10.   0.  10.   0.]]


In [19]:
# 3-dimensional array

c = np.array(
    [[[2, 1, 4],
      [2, 6, 8]],
    
     [[0, 1, 5],
      [7, 8, 9]]])

print(c[0, 1, 2])



8


Where we want to select all elements in one dimension we can use :

__Exception__: If it is the last element , we can omit it. 

In [21]:
print(c[0, 1])

print(c[0, :, 1])

[2 6 8]
[1 6]


## Iterating over multi-dimensional arrays. 
We can iterate over a 1D array in the same way as the data structures we have previously studied.

In [80]:
A = np.array([1, 2, 3, 4, 5])

In [81]:
for a in A:
    print(a)

1
2
3
4
5


To loop through individual elements of a multi-dimensional array, we use a nested loop for each dimension of the array.

In [82]:
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

for row in B:
    print("-----")
    for col in row:
        print(col)

-----
1
2
3
-----
4
5
6


## Manipulating arrays
We can use many of the same operations to manipulate arrays as we use for lists.

However, it is important to note a few subtle differences in how array manipulations behave. 

In [25]:
# Length of an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

b = np.array([[1, 3, 4, 17],
              [3, 21, 2, 12]])


print(len(a))
print(len(b))



TypeError: data type not understood

Note the length is the length of the first dimension (e.g. indexing). 

In [33]:
# Sort an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

b = np.array([[1, 3, 4, 17],
              [3, 21, 2, 12]])

# The function sorted applies to 1D data structures only
print(sorted(a))
print(sorted(b[1]))

# The method sort() applies to arrays of any size
a.sort()
b.sort()

print(a)
print(b)

[1, 2, 3, 3, 4, 12, 17, 21]
[2, 3, 12, 21]
[ 1  2  3  3  4 12 17 21]
[[ 1  3  4 17]
 [ 2  3 12 21]]


Arrays are *immutable* (unchangeable).

Technically you cannot add or delete items of an array. 

However, you can make a *new* array (which may have the same name as the original array), with the values ammended as required: 

#### Appending Arrays 
Appending connects array-like (integer, list....) value  to the *end* of the original array. 

By default, 2D arrays are appended as if joining lists.
The new array is a 1D array

In [112]:
# 2D array
a = np.array([[0], [1], [2]])
print(a)
print()

# 2D array
b = np.array([[3], [4]])
print(b)
print()

# integer
c = 1

print(f"original 2D array shapes: a = {a.shape}, b = {b.shape}")
print()

a = np.append(a, b)
print(a)
print(f"new array shape: {a.shape}")
print()

a = np.append(a, c)
print(a)
print(f"new array shape: {a.shape}")
print()

[[0]
 [1]
 [2]]

[[3]
 [4]]

original 2D array shapes: a = (3, 1), b = (2, 1)

[0 1 2 3 4]
new array shape: (5,)

[0 1 2 3 4 1]
new array shape: (6,)



The axis on which to append an array can be optionally specified.

e.g. 2D array:
 - 0: columns
 - 1: rows

The arrays must have the same shape, except in the dimension corresponding to the specified axis 

In [114]:
# 2D array
a = np.array([[0], [1], [2]])
print(a)
print()

# 2D array
b = np.array([[3], [4]])
print(b)
print()

new2d = np.append(a, b, axis=0)
print(new2d)
print(f"new array shape: {new2d.shape}")

[[0]
 [1]
 [2]]

[[3]
 [4]]

[[0]
 [1]
 [2]
 [3]
 [4]]
new array shape: (5, 1)


For example, in the cell above, if you change `axis=0` to `axis=1`, 
<br>you are trying to connect the side of `a` with length=3 to the side of `b` with length=2.

There are dedicated functions to simplify joining or merging arrays.
<br>If you are interested to expeirment further with joiing arrays you can try out the following functions:
 - `np.concatenate()` : Joins a sequence of arrays along an existing axis.
 - `np.vstack()` or `np.r_[]`: Stacks arrays row-wise
 - `np.hstack()` : Stacks arrays horizontally
 - `np.column_stack()` or `np.c_[]` : Stacks arrays column-wise
Refer to last week's seminar for how to inpterpret the function documentation. 

It can also be useful to remove individual (single or multiple) elements.

For example, the following expand the locations within the array that you can change beyond the location at the *end* of the array.

#### Adding elements to an array

In [68]:
# Add items to an array
# The insert() function arguments are
# 1) The array to insert to
# 2) The index of the inserted element
# 3) The value of the inserted element

a = ([1, 2, 3])
a = np.insert(a, 1, 4)
print(a)

[1 4 2 3]


Notice that, again, the output is a 1D aray by default

In [90]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

print(f"original array shape: {b.shape}")

b = np.insert(b, 1, [4, 4])

print(b)

print(f"new array shape: {b.shape}")

original array shape: (3, 2)
[1 4 4 1 2 2 3 3]
new array shape: (8,)


To preserve the multi-dimensional structure of an array, we can specify the axis on which to insert an element or range of elements. 
<br> In the example below, a column is inserted at element 1 of axis 1. 

In [91]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

b = np.insert(b, 1, [3, 2, 1], axis=1)
print(b)

[[1 3 1]
 [2 2 2]
 [3 1 3]]


Notice what happens when we insert a *single* value on a specified axis

In [92]:
b = np.insert(b, 1, 4, axis=1)
print(b)

[[1 4 3 1]
 [2 4 2 2]
 [3 4 1 3]]


This behaviour is due to a very useful property called *broadcasting*. 
<br>We will study the rules governing broadcasting later in this seminar. 

#### Deleting items from an array

In [34]:
# Items are deleted from their position in a 1D array by default

z = np.array([1, 3, 4, 5, 6, 7, 8, 9])


z = np.delete(z, 3)
print(z)

z = np.delete(z, [0, 1, 2])
print(z)


[ 1  3  4  3 21  2 12]
[ 3 21  2 12]


In [97]:
# Again, axes to delete can be optionally specified:

z = np.array([[1, 3, 4, 5], [6, 7, 8, 9]])
print(z)
print()

z = np.delete(z, 3, axis=1)
print(z)
print()

z = np.delete(z, [0, 1, 2], axis=1)
print(z)
print()

[[1 3 4 5]
 [6 7 8 9]]

[[1 3 4]
 [6 7 8]]

[]



#### Changing items in an array

In [42]:
c = np.array([1, 2, 3])
c[1] = 4
print(c)

[1 4 3]


### Boolean array indexing

Recall that we can use *conditional operators* to check the value of a single variable against a condition.

The value returned is a Boolean True or False value.


In [17]:
a = 4
print('a < 2:', a < 2)
print('a > 2:', a > 2)

a < 2: False
a > 2: True


If we instead use *conditional operators* to check the value of an array against a condition.

The value returned is an *array* of Boolean True or False values.

In [19]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

idx = a > 2

print(idx)

[[False False]
 [ True  True]
 [ True  True]]


A particular elements of an array can be are specified by using a boolean array as an index. 

Only the values of the array where the boolean array is `True` are selected. 

The varaible `idx` can therefore now be used as the index to select all elements greater than 2.

In [20]:
print(a[idx])   

[3 4 5 6]


To do the whole process in a single step

In [11]:
print(a[a > 2]) 

[3 4 5 6]


Use shape to reshape the matrix? 

Another example

In [16]:
a = np.arange(5)
print('the total array:', a)
print('values less than 3:', a[a < 3])

the total array: [0 1 2 3 4]
values less than 3: [0 1 2]


## Mathematics with arrays.

Unlike lists, NumPy arrays support common arithmetic operations, such as addition of two arrays.

In [30]:
# To add the elements of two lists we need the Numpy function: add
a = [1, 2, 3]
b = [4, 5, 6]

c = a + b
print(c)

c = np.add(a, b)
print(c)

[1, 2, 3, 4, 5, 6]
[5 7 9]


To add the elements of two arrays we can just use regular arithmetic operators.

In [117]:
a = np.array([1, 2, 3])
b = np.ones((1,3))

c = a + b
print(c)

[[ 2.  3.  4.]]


Algebraic operations are appled *elementwise* to an array.

This means the function is applied individually to each element in the list.

For addition and subtraction arrays behave like vectors and matrices.

For example, if you were to add or subtract two vectors/matrices in MATLAB. 

In [ ]:
a = np.array([1.0, 0.2, 1.2])
b = np.array([2.0, 0.1, 2.1])

print(a - b)

print(np.subtract(a, b))

But it is important to remember that arrays ARE NOT vectors and matrices.

Regular mathematical operators perform *elementwise* operations on arrays. 

In [41]:
a = np.array([1.0, 0.2, 1.2])
b = np.array([2.0, 0.1, 2.1])

# Elementwise multiplication of a and b
print(a * b)
print(np.multiply(a, b))

print()

# Elementwise division of a and b
print(a / b)
print(np.divide(a, b))

[ 2.    0.02  2.52]
[ 2.    0.02  2.52]

[ 0.5         2.          0.57142857]
[ 0.5         2.          0.57142857]


If the number of __columns in A__ 
<br>is the same as number of __rows in B__, 
<br>we can find the matrix product of $\mathbf{A}$ and $\mathbf{B}$.

\begin{equation*}
\underbrace{
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
}_{\mathbf{A} \text{ 3 rows} \text{ 3 columns}}
\times
\underbrace{
\begin{bmatrix}
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
}_{\mathbf{B} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
(1 \cdot 10 + 2 \cdot 12 + 3 \cdot 14) \quad
(1 \cdot 11 + 2 \cdot 13 + 3 \cdot 15) \\
(4 \cdot 10 + 5 \cdot 12 + 6 \cdot 14) \quad
(4 \cdot 11 + 5 \cdot 13 + 6 \cdot 15) \\
(7 \cdot 10 + 8 \cdot 12 + 9 \cdot 14) \quad
(7 \cdot 11 + 8 \cdot 13 + 9 \cdot 15) \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
76  & 82 \\
184 & 199 \\
292 & 316 \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
\end{equation*}

## Mathematics with Vectors (1D arrays)
Let's look at a  previous example for computing the dot product of two vectors.

The dot product of two $n$-length-vectors:
<br> $ \mathbf{A} = [A_1, A_2, ... A_n]$
<br> $ \mathbf{B} = [B_1, B_2, ... B_n]$

\begin{align}
\mathbf{A} \cdot \mathbf{B} = \sum_{i=1}^n A_i B_i.
\end{align}

We learnt to solve this very easily using a Python `for` loop.

With each iteration of the loop we increase the value of `dot_product` (initial value = 0.0) by the product of `a` and `b`.  

```python
A = [1.0, 3.0, -5.0]
B = [4.0, -2.0, -1.0]

# Create a variable called dot_product with value, 0.
dot_product = 0.0

for a, b in zip(A, B): 
    dot_product += a * b

print(dot_product)
```

Using Numpy arrays we can solve the dot product using the Numpy function `dot`.

In [70]:
A = np.array([1.0, 3.0, -5.0])
B = np.array([4.0, -2.0, -1.0])

print(np.dot(A,B))

3.0


__Try it yourself__

Recap the Seminar 5: Functions; in the cell below write a function that takes two lists and returns the dot product using the code from Seminar 4: Data Structures (shown above).

Use the magic function `%timeit` to compare the speed of the for loop with the Numpy `dot()` function for solving the dot product.

In [71]:
# Write a function for the dot product of two vectors expressed as lists
# Compare the speed of your function to the Numpy function

## Mathematics with Matrices (2D arrays)
If you have previously studied matrices, the operations in this section will be familiar. 

If you have not yet studied matrices, you may want to refer back to this section once matrices have been covered in your mathematics classes.

Material from this section will not be included in the exam.

2D arrays are a convenient way to represents matrices.

For example, to create the matrix

$$
A = 
\begin{bmatrix} 
3 & 5 & 7\\ 
2 & 4 & 6
\end{bmatrix} 
$$


In [76]:
A = np.array([[3, 5, 7], 
              [2, 4, 6]])
print(A)

[[3 5 7]
 [2 4 6]]


Recall, the method `shape()` tells us the dimensions of an array.

This gives us the number of rows and the number of columns, expressed as a tuple.

By describe the dimensions of a matrix as as "rows" by "columns" matrix. 

In [77]:
print(A.shape)
print(f"Number of rows is {A.shape[0]}, number of columns is {A.shape[1]}")
print(f"A is an {A.shape[0]} by {A.shape[1]} matrix")

(2, 3)
Number of rows is 2, number of columns is 3


### Matrix multiplication

If the number of __columns in A__ 
<br>is the same as number of __rows in B__, 
<br>we can find the matrix product of $\mathbf{A}$ and $\mathbf{B}$.


\begin{align}
\mathbf{A} \mathbf{B} = \mathbf{C} 
\end{align}

We multiply each __row__ in \mathbf{A} by each __column__ in \mathbf{B}



\begin{equation*}
\underbrace{
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
}_{\mathbf{A} \text{ 3 rows} \text{ 3 columns}}
\times
\underbrace{
\begin{bmatrix}
b_{11} \\
b_{21} \\
b_{31} \\
\end{bmatrix}
}_{\mathbf{B} \text{  3 rows} \text{  1 column}}
=\underbrace{
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} \\
a_{31}b_{11} + a_{32}b_{21} + a_{33}b_{31} \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  1 column}}
\end{equation*}

In matrix $\mathbf{C}$, the element in 
<br>__row $i$__, 
<br>__column $j$__ 

is equal to the dot product of 
<br>__$i$th row__ of $\mathbf{A}$, 
<br>__$j$th column__ of $\mathbf{B}$.

Matrix $\mathbf{C}$ therefore has 
<br>the same number of __rows as A__,
<br>the same number of __columns as B__.

#### Example 1: THIS EXAMPLE IS WRONG MAKE A GOOD ONE!!!

<img src="img/MatrixProduct.png" alt="Drawing" style="width: 500px;"/>

#### Example 2:
\begin{equation*}
\underbrace{
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
}_{\mathbf{A} \text{ 3 rows} \text{ 3 columns}}
\times
\underbrace{
\begin{bmatrix}
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
}_{\mathbf{B} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
(1 \cdot 10 + 2 \cdot 12 + 3 \cdot 14) \quad
(1 \cdot 11 + 2 \cdot 13 + 3 \cdot 15) \\
(4 \cdot 10 + 5 \cdot 12 + 6 \cdot 14) \quad
(4 \cdot 11 + 5 \cdot 13 + 6 \cdot 15) \\
(7 \cdot 10 + 8 \cdot 12 + 9 \cdot 14) \quad
(7 \cdot 11 + 8 \cdot 13 + 9 \cdot 15) \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
76  & 82 \\
184 & 199 \\
292 & 316 \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
\end{equation*}

In [91]:
#Example 1
A = np.array([[1, 1, 2],
              [2, 1, 3],
              [1, 4, 2]])

B = np.array([[3], 
              [1], 
              [2]])

C = A.dot(B)
print(C)

print()

C = np.dot(A,B)
print(C)

[[ 8]
 [13]
 [11]]

[[ 8]
 [13]
 [11]]


In [93]:
#Example 2
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[10, 11], 
              [12, 13], 
              [14, 15]])

C = A.dot(B)
print(C)

print()

C = np.dot(A,B)
print(C)

[[ 76  82]
 [184 199]
 [292 316]]

[[ 76  82]
 [184 199]
 [292 316]]


We can find the inverse $\mathbf{A}^{-1}$, of a sqaure matrix, $\mathbf{A}$. 

In [99]:
A = np.array([[1,2], 
              [3, 4]]) 

Ainv = np.linalg.inv(A)

print(f"A = \n {A}")
print(f"Inverse of A = \n {Ainv}")

A = 
 [[1 2]
 [3 4]]
Inverse of A = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


We can find the determinant, $\textrm{det}(\mathbf{A})$, of a sqaure matrix, $\mathbf{A}$. 

In [102]:
A = np.array([[1,2], 
              [3, 4]]) 

Adet = np.linalg.det(A)

print(f"A = \n {A}")
print(f"Determinant of A = {round(Adet, 2)}")

A = 
 [[1 2]
 [3 4]]
Determinant of A = -2.0


We can find the trasnpose $\mathbf{A^T}$ of a matrix $\mathbf{A}$.

- The columns of the transpose matrix are the rows of the original matrix.
- The rows of the transopse matrix are the columns of the original matrix.  

In [199]:
a = np.zeros((2,4))
print(a)
print()


print(a.T)
print()

#or 

print(np.transpose(a))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


We can generate an *identity matrix*.

In [103]:
I = np.eye(2)
print(I)

print()

I = np.eye(4)
print(I)

[[ 1.  0.]
 [ 0.  1.]]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [ ]:
print(np.sqrt(a))
print(a ** (1/2))


## Vectorising Functions

Numpy functions applied to a single array, will be performed on each element in the array. 

The function takes an array of values as an input argument.

In [ ]:
print(np.sqrt(a))
print(a ** (1/2))


For example, we can apply trigonometric functions, elementwise, to arrays, lists and tuples.

In [65]:
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
y = [0.0, np.pi/2, np.pi, 3*np.pi/2]
z = (0.0, np.pi/2, np.pi, 3*np.pi/2)

print(np.sin(x))
print(np.cos(y))
print(np.tan(z))


[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00]
[  1.00000000e+00   6.12323400e-17  -1.00000000e+00  -1.83697020e-16]
[  0.00000000e+00   1.63312394e+16  -1.22464680e-16   5.44374645e+15]


An array of values does not work as an input for all functions.

In [40]:
def func(x):
    if x < 0:
        f = 2 * x
    else:
        f = 3 * x
    return f

x = np.array([2,2])
y = func(x) # Run this line after removing the # to se

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

This doesn't work because Python doesn't know what to do with the line 

`if x < 0` 

when `x` contains many values. 

For some values of `x` the `if` statement may be `True`, for others it may be `False`. 



A simple way around this problem is to vectorise the function. 

We create a new function that is a *vectorized* form of the original function.

The new function and can be called with an array as an argument.  

In [41]:
funcvec = np.vectorize(func)

x = np.random.randint(4,size =(2,2))

y = funcvec(x)
print(x)
print(y)

[[3 0]
 [2 3]]
[[9 0]
 [6 9]]


## Broadcasting

Another source of incompatibility that you are likely to encounter is in trying to use arrays with different shapes for arithmetic operations. 

For example, you have one array that larger and another array that is smaller.
<br>You may want to use the smaller array multiple times to perform an operation (such as a sum, multiplication, etc.) on the larger array.

This is achieved using the broadcasting mechanism. 

The arrays can be broadcast together if all dimensions of the arrays are *compatible*


##### Dimensions are compatible when they are equal.

Consider the example below. `x` and `y` are the same shape, so we can addd them.

In [122]:
x = np.ones((3,4))
print(x.shape)

y = np.full((3,4), 4)
print(y.shape)

# Add `x` and `y`
x + y

(3, 4)
(3, 4)


array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

##### Dimensions are compatible when the length of at least one of them is equal to 1.

<img src="img/broadcasting1x3.gif" alt="Drawing" style="width: 300px;"/>


In [164]:
# 1 x 3 array
a = np.arange(1,4)

# integer
b = 2

# 1 x 3 array
result = a * b

print(a)
print()
print(b)
print()
print(result)

[1 2 3]

2

[2 4 6]


In the dimension where `b` has size 1 and `a` has a size greater than 1 (i.e. 3), `b` behaves as if it were copied along that dimension.

In [166]:
# 4 x 1 array
x = np.array([[0],
              [10],
              [20],
              [30]])

# 1 x 3 array
y = np.ones(3)

# 4 x 3 array
a = x * y

print(x)
print()
print(y)
print()
print(a)


[[ 0]
 [10]
 [20]
 [30]]

[ 1.  1.  1.]

[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]


<img src="img/broadcasting4x3.gif" alt="Drawing" style="width: 300px;"/>

In [168]:
# a: 4 x 3 array (see cell above)

# 1 x 3 array
b = np.arange(3)

# 4 x 3 array
result = a + b

print(a)
print()
print(b)
print()
print(result)

[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]

[0 1 2]

[[  0.   1.   2.]
 [ 10.  11.  12.]
 [ 20.  21.  22.]
 [ 30.  31.  32.]]


The size of the output array is the maximum size along each dimension of the input arrays.

The 4x3 and 1x4 arrays shown in the cell below cannot be broadcast together.
<br>The dimensions 3 and 4 are incompatible.

<img src="img/broadcasting_mismatch.gif" alt="Drawing" style="width: 300px;"/>

Note that if the array dimensions are incompatible, it will generate a ValueError.

Recall, the function `np.insert` that we used earlier.

An integer (length=1) can be broadcast into an array of any size. 

In [129]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

b = np.insert(b, 1, 4, axis=1)
print(b)

[[1 4 1]
 [2 4 2]
 [3 4 3]]


In [ ]:
Here are some examples of practical applications of broadcasting.

### Broadcasting Example: Calorie Calculator

Let's say we have a large data set; each datum is a list of parameters.

Example datum: a type of food and the the amount of fat, protein and carbohydrate in a serving of that food.

Our data set of food nutrients might look something like the table below:

|Food (100g) |Fat(g)|Protein (g)|Carbohydrate (g)|
|------------|----- |-----------|----------------|
|Almonds     |    49|         21|              22|                         
|Peas        |     0|          5|              14|   
|Avocado     |    15|          2|               9|
|Kale        |     1|          3|              10|  

By applying the following sclaing factors, we can calculate the number of calories in a food type due to fat, protein and carbohydrate:
 -  fat: 9 cal/g
 -  protein: 4 cal/g
 -  carbohydrate 4 cal/g
 
Using what we have studied so far, we could convert the table to calories using a loop:
```python

nutrients = np.array([[49, 21, 22],
                      [0,   5, 14],
                      [15,  2,  9],
                      [ 1,  3, 10]])

cal_convert = np.array([9, 4, 4])

calories = np.empty((4,3))

for index, value in enumerate(nutrients):
    calories[index] = value * cal_convert
    
```
However, it is faster and more concise to broadcast the two arrays together:        


In [184]:
nutrients = np.array([[49, 21, 22],
                      [0,   5, 14],
                      [15,  2,  9],
                      [ 1,  3, 10]])

cal_convert = np.array([9, 4, 4])

calories = nutrients * cal_convert

print(calories)

[[441  84  88]
 [  0  20  56]
 [135   8  36]
 [  9  12  40]]


### Broadcasting Example: Vector Quantisation Algorithm
This is a simple algorithm used for catagorisation.
<br>It determines which catagory a data point should belong to from its closest proximity to a set of values representing possible catagories.
<br>Each value represents the mean of the corresponding catagory.

<br>For example, colour quantisation is used in image processing reduces the number of distinct colors used in an image, while maintianing visual similarity to the original image. 

<table><tr><td> 
<img src="img/un_quantised_cat.png" alt="Drawing" style="width: 300px;"/> </td><td> 
<img src="img/quantised_cat.png" alt="Drawing" style="width: 300px;"/> </td><td> 
</table>

CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=1477223



<br>In the plot below, each of the circles represents the mean height and weight of athletes grouped by type. 
<br>The square represents the height and weight of an athlete to be classified. 
<img src="img/vector_quantisation.png" alt="Drawing" style="width: 500px;"/>
To find the closet point:
1. Use broadcasting to find the difference between the position of the __square__ and the position of each __circle__ in the x and y directions. <br>
1. Find the distance, $d$ from the square, $s$ to each circle, $c$ using: <br>$d = \sqrt{(x_{c}-x_{s})^2 + (y_{c}-y_{s})^2}$ <br>
1. Choose the group corresponding to the minimum distance, $d_{min}$

In [197]:
athlete = np.array([111.0,188.0])

categories = np.array([[102.0, 203.0],
                       [132.0, 193.0],
                       [45.0, 155.0],
                       [57.0, 173.0]])

# 1. broadcast
diff = categories - athlete

# 2. distance to each point (magnitude of values along axis 1 for each datum)
# dist = np.linalg.norm(diff,axis=1)
dist = np.sqrt(np.sum(diff**2,axis=1))

# 3. which group?
nearest = np.argmin(dist)
print(nearest)

0


The nearest group is index 0 of the array `catagories`.
<br>Based on mean height and weight, the athlete is most likely to be a basketball player.

## Resizing and Reshaping
We can change the size of an array in each dimension.

For example, you may want to edit the length of a dimension of an array to make it compatible with another array for broadcasting.

### Resizing
We can resize an array. 
<br>If the new array size is smaller, the original array will be trimmed to the new size.

In [207]:
a=np.array([[0,1],
            [2,3]])

b = np.resize(a,(2,1))
print(b)
print()

a.resize(2,1)
print(a)

[[0]
 [1]]

[[0]
 [1]]


If the new array size is larger, the extra space can either be filled with repeating copies of the original array.

In [209]:
a=np.array([[0,1],
            [2,3]])

b = np.resize(a,(4,4))
print(b)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


or with zeros.

In [211]:
a=np.array([[0,1],
            [2,3]])

a.resize(4,4)
print(a)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Reshaping
You can re-shape the array. 
The new array must have the __same number of elements__ as the original array.

__Example:__ Using range to create a column vector:

In [236]:
x = np.arange(0, 31, 10)
y = x.reshape((4,1))

# which can be written in one line as:
z = np.arange(0, 31, 10).reshape((4,1))

print(x)
print()
print(y)
print()
print(z)

[ 0 10 20 30]

[[ 0]
 [10]
 [20]
 [30]]

[[ 0]
 [10]
 [20]
 [30]]


In [229]:
#Example 1
A = np.array([[1, 1, 2, 1],
              [2, 1, 3, 1],
              [2, 1, 3, 1],
              [1, 4, 2, 1]])


#C = z.dot(A)
print(C)

print()

C = np.dot(z,z)
print(C)

1400



ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [158]:
x = np.arange(0, 31, 10)
np.reshape(x, (4, 1))
print(x)
print(x.shape)


print(x)


print(y)

# y = np.ones(3)
# print(y.shape)

# z = x * y
# print(z.shape)
# print(z)


[ 0 10 20 30]
(4,)
[[ 0]
 [10]
 [20]
 [30]]
[[ 0]
 [10]
 [20]
 [30]]


## Review Exercises

The folowing exercises are provided to practise what you have learnt in today's seminar.

There are some extension excercises for you to complete if you are familiar with using matrices and want to practise matrix manipulation using Python.

If you have not yet studeied matrices, you can come back to this section when the mathematics used is more familiar to you. 



### Review Exercise: Arrays and indices

In the cell below:

1. Create an array of zeros with length 25. 

2. Change the first 10 values to 5. 

3. Change the next 10 values to a sequence starting at 12 and increasig with steps of 2 to 30 - do this with one command. 

4. Set the final 5 values to 30. 

### Review Exercise:  Two-dimensional array indices

In the cell below, for the array `x`, write code to print: 

* the first row of `x`
* the first column of `x`
* the third row of `x`
* the last two columns of `x`
* the four values in the upper right hand corner of `x`
* the four values at the center of `x`


In [3]:
x = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [2, 4, 1, 3],
              [4, 1, 2, 3]])

### Review Exercise:  Fix the error 
The code below, is supposed to:
- change the last 5 values of the array `x` to the values [50, 52, 54, 56, 58] 
- print the result

There are some errors in the code. 

Remove the comment markers and run the code to see the error message. 

Then fix the code and run it again.