In [6]:
from IPython.core.display import HTML
def css_styling():
    styles = open("./styles/custom.css", "r").read()
    return HTML(styles)
css_styling()

### BEFORE YOU DO ANYTHING...
In the terminal:
1. Navigate to __inside__ your ILAS_Python repository.
2. __COMMIT__ any un-commited work on your personal computer.
3. __PULL__ any changes *you* have made using another computer.
4. __PULL__ textbook updates (including homework answers).

1. __Open Jupyter notebook:__   Start >> Programs (すべてのプログラム) >> Programming >> Anaconda3 >> JupyterNotebook
1. __Navigate to the ILAS_Python folder__. 
1. __Open Seminar 7___  by clicking on 7_Numerical_computation_with_Numpy.

<h1>Numerical Computation with Numpy</h1> 

<h1>Lesson Goal</h1> 

Compose programs to solve simple mathematical problems using the Python Numpy package. 

## Objectives
- Represent data using the `array` data structure for numerical computation.
- Use 1D and 2D arrays to represent vectors and matrices. 
- Manipulate arrays (indexing, slicing, vectorising etc)
- Perform familiar numerical operations using Python.
- Compare efficiency of vectorised and non-vectorised functions.

## Why are we studying this?
Numerical computation is central to almost all scientific and engineering problems.

There are programming languages specifically designed for numerical computation:
- Fortran
- MATLAB

There are libaries dedicated to efficient numerical computations:
- Numpy
- Scipy
- Sympy ...

NumPy (http://www.numpy.org/) 
 - The most widely used Python library for numerical computations. 
 - Large, extensive library of data structures and functions for numerical computation.
 - Useful for perfoming operation you will learn on mathematics-based courses.


Scipy (https://www.scipy.org/)
- Builds on Numpy, additional functionality
- More specialised data structures and functions over NumPy.




If you are familiar with MATLAB, NumPy and SciPy provide similar functionality. 



Last week we covered an introduction to some basic functions of Numpy.

NumPy is a very extensisve library.

This seminar will:
- Introduce some useful functions
- Briefly discuss how to search for additional functions you may need. 

your best resources are search engines, such as http://stackoverflow.com/.



## Importing the NumPy module

To make NumPy functions and variables available to use in our program in our programs, we need to __import__ it using.

`import numpy`

We typically import all modules at the start of a program or notebook. 

The shortened name `np` isoften used for numpy. 

In [7]:
import numpy as np

## Data Structure: The Numpy `array`

### Why do we need another data structure?

Python lists hold 'arrays' of data. 

Lists are very flexible. e.g. holding mixed data type.

There is a trade off between flexibility and performance e.g. speed.

Science engineering and mathematics problems often involve large amounts of data and numerous operations. 

We therefore use specialised functions and data structures for numerical computation.

## Numpy array

A numpy array is a grid of values, *all of the same type*.

To create an array we use the Numpy `array` function.

It takes a list as an argument.

In [8]:
a = np.array([1, 2, 3])

print(type(a))

print(a.dtype)

<class 'numpy.ndarray'>
int64


In [9]:
b = [4.0, 5, 6.0]

c = np.array(b) 

print(type(b))
print(type(c))
print(c.dtype)

<class 'list'>
<class 'numpy.ndarray'>
float64


## Multi-dimensional arrays.

Unlike the data types we have studied so far, arrays can have multiple dimensions.

__`rank`:__ the number of *dimensons* of the array.

__`shape`:__ a *tuple* of *integers* giving the *size* of the array along each *dimension*.

In [10]:
# 1-dimensional array
a = np.array([1, 2, 3])

# 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

c = np.array(
    [[[1, 1],
      [1, 1]],
     
     [[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

print(c.shape)

(2, 2, 2)
(3, 2, 2)


In [12]:
# 3-dimensional array

c = np.array(
    [[[1, 1],
      [1, 1]],
    
     [[1, 1],
      [1, 1]]])

# 4-dimensional array
d = np.array(
    [[[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]],


      [[[1, 1],
       [1, 1]],
      
      [[1, 1],
       [1, 1]]]])

print(c.shape)
print(d.shape)

(2, 2, 2)
(2, 2, 2, 2)


## Creating a numpy array.

There are several other ways we can create an array

In [13]:
# Create an array of all zeros
# The zeros() function argument is the shape.
# Shape: tuple of integers giving the size along each dimension.

a = np.zeros(5)
print(a)

print()

a = np.zeros((2,2))   
print(a)  

[ 0.  0.  0.  0.  0.]

[[ 0.  0.]
 [ 0.  0.]]


In [14]:
# Create an array of all ones

b = np.ones(5)
print(b)

print()

b = np.ones((1,2))    
print(b)  

[ 1.  1.  1.  1.  1.]

[[ 1.  1.]]


In [15]:
# Create a constant array
# The second function argument is the constant value

c = np.full(6, 8)
print(c)

print()

c = np.full((2,2,2), 7)  
print(c)               


[8 8 8 8 8 8]

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [16]:
# Create an array filled with random values

e = np.random.rand(6)
print(e)

print()

e = np.random.random((2,2))  
print(e)

print()

e = np.random.randint(16, size=(4,4))
print(e)

print()

e = np.random.randint(8, size=(2, 2, 2))
print(e)

[ 0.85172471  0.8399638   0.78430877  0.22117159  0.59024844  0.52306961]

[[ 0.77130148  0.72136067]
 [ 0.96344053  0.67477549]]

[[ 1  0 14  4]
 [ 5  0 10 10]
 [ 0  0 15  2]
 [ 9 14  6  7]]

[[[4 7]
  [6 0]]

 [[3 6]
  [5 0]]]


## Indexing.

We can index into an array exactly the same way as the other data structures we have studied.

In [17]:
x = np.array([1, 2, 3, 4, 5])

print(x[4])

print(x[2:])

5
[3, 4, 5]


For an n-dimensional matrix we need n index values to address an element or range of elements.

Note the order in which dimensions are addressed.

In [18]:
# 2 dimensional array

y = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(y[1,2])

print(y[1:, 0:2])

6
[[4 5]]


In [19]:
# 3-dimensional array

c = np.array(
    [[[2, 1, 4],
      [2, 6, 8]],
    
     [[0, 1, 5],
      [7, 8, 9]]])

print(c[0, 1, 2])



8


Where we want to select all elements in one dimension we can use :

__Exception__: If it is the last element , we can omit it. 

In [21]:
print(c[0, 1])

print(c[0, :, 1])

[2 6 8]
[1 6]


## Iterating over multi-dimensional arrays. 
We can iterate over a 1D array in the same way as the data structures we have previously studied.

In [80]:
A = np.array([1, 2, 3, 4, 5])

In [81]:
for a in A:
    print(a)

1
2
3
4
5


To loop through individual elements of a multi-dimensional array, we use a nested loop for each dimension of the array.

In [82]:
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

for row in B:
    print("-----")
    for col in row:
        print(col)

-----
1
2
3
-----
4
5
6


## Manipulating arrays
We can use many of the same operations to manipulate arrays as we use for lists.

In [75]:
# Length of an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

b = ([1, 3, 4, 17],
     [3, 21, 2, 12])


print(len(a))
print(len(b))



8
2


Note the length is the length of the first dimension (e.g. indexing). 

In [74]:
# Sort an array

a = np.array([1, 3, 4, 17, 3, 21, 2, 12])

# The method sort() and function sorted() give the same result
a.sort()

a = sorted(a)

print(a)

[1, 2, 3, 3, 4, 12, 17, 21]


Arrays are *immutable* (unchangeable).

Technically you cannot delete an item from it. 

However, you can make a new array without the values you don't want: 

In [34]:
# Remove items from an array

z = np.array([1, 3, 4, 17, 3, 21, 2, 12])


z = np.delete(z, 3)
print(z)

z = np.delete(z, [0, 1, 2])
print(z)


[ 1  3  4  3 21  2 12]
[ 3 21  2 12]


In [38]:
# Add items to an array

a = ([1, 2, 3])
a = np.insert(a, 1, 4)
print(a)

[1 4 2 3]


In [39]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

b = np.insert(b, 1, 4)
print(b)

[1 4 1 2 2 3 3]


In [41]:
# Add items to an array

b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

b = np.insert(b, 1, 4, axis=1)
print(b)

[[1 4 1]
 [2 4 2]
 [3 4 3]]


In [42]:
# Change items in an array

c = np.array([1, 2, 3])
c[1] = 4
print(c)

[1 4 3]


### Boolean array indexing

Boolean indexing selects elements that satisfy a condition:  

In [49]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

bool = a > 2

print(bool) 

# The varaible bool can now be used as the index to select all elements 
# greater than 2.
print(a[bool_idx])  

# To do this in a single statement: 
print(a[a > 2])     

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Mathematics with arrays.

Unlike lists, NumPy arrays support common arithmetic operations, such as addition of two arrays.

In [59]:
# To add the elements of two lists we need the Numpy function: add
x = [1.0, 0.2, 1.2]
y = [2.0, 0.1, 2.1]
print(x)
print(y)

# Sum x and y
z = x + y
print(z)

# Sum x and y
z = np.add(x, y)
print(z)

[1.0, 0.2, 1.2]
[2.0, 0.1, 2.1]
[1.0, 0.2, 1.2, 2.0, 0.1, 2.1]
[ 3.   0.3  3.3]


In [60]:
# To add the elemnts of two arrays we can just use regular arithmetic operators
x = np.array([1.0, 0.2, 1.2])
y = np.array([2.0, 0.1, 2.1])
print(x)
print(y)

# Sum x and y
z = x + y
print(z)

# We can also use the Numpy function, add
z = np.add(x, y)
print(z)

[ 1.   0.2  1.2]
[ 2.   0.1  2.1]
[ 3.   0.3  3.3]
[ 3.   0.3  3.3]


In [62]:
print(x - y)
print(np.subtract(x, y))

print()

print(x * y)
print(np.multiply(x, y))

print()

print(x / y)
print(np.divide(x, y))

print()

print(np.sqrt(x))
print(x ** (1/2))

print()

print(x ** 2)

[-1.   0.1 -0.9]
[-1.   0.1 -0.9]

[ 2.    0.02  2.52]
[ 2.    0.02  2.52]

[ 0.5         2.          0.57142857]
[ 0.5         2.          0.57142857]

[ 1.          0.4472136   1.09544512]
[ 1.          0.4472136   1.09544512]

[ 1.    0.04  1.44]


Numpy functions are appled elementwise to an array.

This means the function is applied individually to each element in the list.

For example, we can apply trigonometric functions, elementwise, to arrays, lists and tuples.

In [65]:
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
y = [0.0, np.pi/2, np.pi, 3*np.pi/2]
z = (0.0, np.pi/2, np.pi, 3*np.pi/2)

print(np.sin(x))
print(np.cos(y))
print(np.tan(z))


[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00]
[  1.00000000e+00   6.12323400e-17  -1.00000000e+00  -1.83697020e-16]
[  0.00000000e+00   1.63312394e+16  -1.22464680e-16   5.44374645e+15]


## Vectorising Functions
Because the outcome of this is that a 1D array behave like a vector, we call this *vectorisation*. 

Vectorisation can make a significant difference in the time taken to compute a value.

## Mathematics with Vectors (1D arrays)
Let's look at a  previous example for computing the dot product of two vectors.

The dot product of two $n$-length-vectors:
<br> $ \mathbf{A} = [A_1, A_2, ... A_n]$
<br> $ \mathbf{B} = [B_1, B_2, ... B_n]$

\begin{align}
\mathbf{A} \cdot \mathbf{B} = \sum_{i=1}^n A_i B_i.
\end{align}

We learnt to solve this very easily using a Python `for` loop.

With each iteration of the loop we increase the value of `dot_product` (initial value = 0.0) by the product of `a` and `b`.  

```python
A = [1.0, 3.0, -5.0]
B = [4.0, -2.0, -1.0]

# Create a variable called dot_product with value, 0.
dot_product = 0.0

for a, b in zip(A, B): 
    dot_product += a * b

print(dot_product)
```

Using Numpy arrays we can solve the dot product using the Numpy function `dot`.

In [70]:
A = np.array([1.0, 3.0, -5.0])
B = np.array([4.0, -2.0, -1.0])

print(np.dot(A,B))

3.0


__Try it yourself__

Recap the Seminar 5: Functions; in the cell below write a function that takes two lists and returns the dot product using the code from Seminar 4: Data Structures (shown above).

Use the magic function `%timeit` to compare the speed of the for loop with the Numpy `dot()` function for solving the dot product.

In [71]:
# Write a function for the dot product of two vectors expressed as lists
# Compare the speed of your function to the Numpy function

## Mathematics with Matrices (2D arrays)
If you have previously studied matrices, the operations in this section will be familiar. 

If you have not yet studied matrices, you may want to refer back to this section once matrices have been covered in your mathematics classes.

Material from this section will not be included in the exam.

2D arrays are a convenient way to represents matrices.

For example, to create the matrix

$$
A = 
\begin{bmatrix} 
3 & 5 & 7\\ 
2 & 4 & 6
\end{bmatrix} 
$$


In [76]:
A = np.array([[3, 5, 7], 
              [2, 4, 6]])
print(A)

[[3 5 7]
 [2 4 6]]


Recall, the method `shape()` tells us the dimensions of an array.

This gives us the number of rows and the number of columns, expressed as a tuple.

By describe the dimensions of a matrix as as "rows" by "columns" matrix. 

In [77]:
print(A.shape)
print(f"Number of rows is {A.shape[0]}, number of columns is {A.shape[1]}")
print(f"A is an {A.shape[0]} by {A.shape[1]} matrix")

(2, 3)
Number of rows is 2, number of columns is 3


### Matrix multiplication

If the number of __columns in A__ 
<br>is the same as number of __rows in B__, 
<br>we can find the matrix product of $\mathbf{A}$ and $\mathbf{B}$.


\begin{align}
\mathbf{A} \mathbf{B} = \mathbf{C} 
\end{align}

We multiply each __row__ in \mathbf{A} by each __column__ in \mathbf{B}



\begin{equation*}
\underbrace{
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
}_{\mathbf{A} \text{ 3 rows} \text{ 3 columns}}
\times
\underbrace{
\begin{bmatrix}
b_{11} \\
b_{21} \\
b_{31} \\
\end{bmatrix}
}_{\mathbf{B} \text{  3 rows} \text{  1 column}}
=\underbrace{
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} \\
a_{31}b_{11} + a_{32}b_{21} + a_{33}b_{31} \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  1 column}}
\end{equation*}

In matrix $\mathbf{C}$, the element in 
<br>__row $i$__, 
<br>__column $j$__ 

is equal to the dot product of 
<br>__$i$th row__ of $\mathbf{A}$, 
<br>__$j$th column__ of $\mathbf{B}$.

Matrix $\mathbf{C}$ therefore has 
<br>the same number of __rows as A__,
<br>the same number of __columns as B__.

#### Example 1: THIS EXAMPLE IS WRONG MAKE A GOOD ONE!!!

<img src="img/MatrixProduct.png" alt="Drawing" style="width: 500px;"/>

#### Example 2:
\begin{equation*}
\underbrace{
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
}_{\mathbf{A} \text{ 3 rows} \text{ 3 columns}}
\times
\underbrace{
\begin{bmatrix}
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
}_{\mathbf{B} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
(1 \cdot 10 + 2 \cdot 12 + 3 \cdot 14) \quad
(1 \cdot 11 + 2 \cdot 13 + 3 \cdot 15) \\
(4 \cdot 10 + 5 \cdot 12 + 6 \cdot 14) \quad
(4 \cdot 11 + 5 \cdot 13 + 6 \cdot 15) \\
(7 \cdot 10 + 8 \cdot 12 + 9 \cdot 14) \quad
(7 \cdot 11 + 8 \cdot 13 + 9 \cdot 15) \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
=\underbrace{
\begin{bmatrix}
76  & 82 \\
184 & 199 \\
292 & 316 \\
\end{bmatrix}
}_{\mathbf{C} \text{  3 rows} \text{  2 columns}}
\end{equation*}

In [91]:
#Example 1
A = np.array([[1, 1, 2],
              [2, 1, 3],
              [1, 4, 2]])

B = np.array([[3], 
              [1], 
              [2]])

C = A.dot(B)
print(C)

print()

C = np.dot(A,B)
print(C)

[[ 8]
 [13]
 [11]]

[[ 8]
 [13]
 [11]]


In [93]:
#Example 2
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[10, 11], 
              [12, 13], 
              [14, 15]])

C = A.dot(B)
print(C)

print()

C = np.dot(A,B)
print(C)

[[ 76  82]
 [184 199]
 [292 316]]

[[ 76  82]
 [184 199]
 [292 316]]


We can find the inverse $\mathbf{A}^{-1}$, of a sqaure matrix, $\mathbf{A}$. 

In [99]:
A = np.array([[1,2], 
              [3, 4]]) 

Ainv = np.linalg.inv(A)

print(f"A = \n {A}")
print(f"Inverse of A = \n {Ainv}")

A = 
 [[1 2]
 [3 4]]
Inverse of A = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


We can find the determinant, $\textrm{det}(\mathbf{A})$, of a sqaure matrix, $\mathbf{A}$. 

In [102]:
A = np.array([[1,2], 
              [3, 4]]) 

Adet = np.linalg.det(A)

print(f"A = \n {A}")
print(f"Determinant of A = {round(Adet, 2)}")

A = 
 [[1 2]
 [3 4]]
Determinant of A = -2.0


We can generate an *identity matrix*.

In [103]:
I = np.eye(2)
print(I)

print()

I = np.eye(4)
print(I)

[[ 1.  0.]
 [ 0.  1.]]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
